version: '3'

services:
    mongo-db:
        container_name: ${MONGO_DATABASE}
        image: mongo:6.0
        volumes:
            - poke-vol:/data/db
        # ports:
        #     - 27017:27017
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        command: [ '--auth' ]

    mongo-express:
        depends_on:
            - mongo-db
        image: mongo-express:1.0.0-alpha.4
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: ${MONGO_DATABASE}
        ports:
            - 8080:8081
        restart: always

    poke-app:
        depends_on:
            - mongo-db
            - mongo-express
        container_name: poke-app-nest
        image: klerith/pokemon-nest-app:1.0.0
        ports:
            - 3000:3000
        environment:
            MONGODB: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DATABASE}:27017
            DB_NAME: ${MONGO_DATABASE}
        restart: always

volumes:
    poke-vol:
        external: false
